# ===== Server =====
server.port=8080

# ===== H2 (file) =====
spring.datasource.url=jdbc:h2:file:./data/tasksdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== H2 Console =====
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===== Thymeleaf (optional) =====
spring.thymeleaf.cache=false

management.endpoints.web.exposure.include=mappings
spring.mvc.trailing-slash.matching=true

logging.level.org.springframework.web.servlet.DispatcherServlet=TRACE
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE